# docker-compose.yml — from-ext первым, to-ext с задержкой
x-basic-logging: &basic-logging
  logging:
    driver: "json-file"
    options:
      max-size: "32mb"

services:
  # ПЕРВЫЙ: from-ext (com → ext)
  from-ext:
    <<: *basic-logging
    image: git-sync:latest
    container_name: from-ext
    volumes:
      - ./configs/from-ext.yaml:/app/src/config.yaml:ro
      - git-sync-tmp-from-ext:/tmp/git-sync
    restart: always

  # ВТОРОЙ: to-ext (ext → com) — задержка 5 мин
  to-ext:
    <<: *basic-logging
    image: git-sync:latest
    container_name: to-ext
    volumes:
      - ./configs/to-ext.yaml:/app/src/config.yaml:ro
      - git-sync-tmp-to-ext:/tmp/git-sync
    restart: always
    depends_on:
      from-ext:
        condition: service_started  
    command: >
      sh -c "
        sleep 30;
        exec python3 /app/src/main.py
      "

volumes:
  git-sync-tmp-to-ext:
  git-sync-tmp-from-ext:
